{{- if .Values.operator.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-agents-operator
  namespace: {{ include "kube-agents.namespace" . }}
  labels:
    {{- include "kube-agents.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
{{- end }}
