{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ include "kube-agents.namespace" . }}
  labels:
    {{- include "kube-agents.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      name: postgres
{{- end }}
